/*
 * client.c - RPC client for remote system monitoring.
 */

#include <rpc/rpc.h>
#include <stdio.h>
#include <stdlib.h>

#include "date.h" /* generated by rpcgen from date.x */

static int menu(void)
{
    int choice;
    printf("===========================================\n");
    printf(" |       Remote System Monitor (RPC)|\n");
    printf("-------------------------------------------\n");
    printf(" 1. Date\n");
    printf(" 2. Time\n");
    printf(" 3. Date + Time\n");
    printf(" 4. CPU usage\n");
    printf(" 5. Memory usage\n");
    printf(" 6. Load + procs\n");
    printf(" 7. Logged-in users\n");
    printf(" 8. All stats\n");
    printf(" 9. Quit\n");
    printf("-------------------------------------------\n");
    printf("Choice (1-9): ");

    if (scanf("%d", &choice) != 1) {
        /* input error */
        return 9;
    }
    printf("===========================================\n");
    return choice;
}

static void print_stats(int option, const rpcstat_stats *st)
{
    if (!st) {
        printf("(no response)\n");
        return;
    }

    switch (option) {
    case 1:
    case 2:
    case 3:
        printf("Time: %s\n", st->timestr ? st->timestr : "");
        break;
    case 4:
        printf("CPU usage: %.2f %%\n", st->cpu_percent);
        break;
    case 5:
        printf("Memory usage: %.2f %%\n", st->mem_percent);
        break;
    case 6:
        printf("Load (1-min): %.2f\n", st->load1);
        printf("Processes: %d running / %d total\n", st->procs_running, st->procs_total);
        break;
    case 7:
        printf("Logged-in user sessions: %d\n", st->user_count);
        printf("Users (unique): %s\n", st->users ? st->users : "");
        break;
    case 8:
    default:
        if (st->timestr && st->timestr[0] != '\0') {
            printf("Time: %s\n", st->timestr);
        }
        printf("CPU usage: %.2f %%\n", st->cpu_percent);
        printf("Memory usage: %.2f %%\n", st->mem_percent);
        printf("Load (1-min): %.2f\n", st->load1);
        printf("Processes: %d running / %d total\n", st->procs_running, st->procs_total);
        printf("Logged-in user sessions: %d\n", st->user_count);
        printf("Users (unique): %s\n", st->users ? st->users : "");
        break;
    }
}

int main(int argc, char **argv)
{
    if (argc != 2) {
        fprintf(stderr, "usage: %s <server-hostname>\n", argv[0]);
        return 1;
    }

    char *server = argv[1];

    /* Create the client handle (UDP as in the sample) */
    CLIENT *cl = clnt_create(server, RPCSTAT_PROG, RPCSTAT_VERS, "udp");
    if (cl == NULL) {
        clnt_pcreateerror(server);
        return 2;
    }

    while (1) {
        int choice = menu();
        if (choice == 9) {
            break;
        }

        rpcstat_request req;
        req.option = choice;

        rpcstat_stats *resp = rpcstat_1(&req, cl);
        if (resp == NULL) {
            clnt_perror(cl, server);
            break;
        }

        print_stats(choice, resp);
        printf("\n");
    }

    clnt_destroy(cl);
    return 0;
}
